/* SPDX-FileCopyrightText: 2026 yuska (GitHub: @yuska1114) */
/* SPDX-License-Identifier: GPL-3.0-or-later */
#ifndef INTEGRAL_GB_RUNTIME_PROTOCOL_H
#define INTEGRAL_GB_RUNTIME_PROTOCOL_H

#include <stdint.h>

#define INTEGRAL_GB_RUNTIME_PROTOCOL_VERSION 2u
#define INTEGRAL_GB_RUNTIME_VERSION "1.1"
#define INTEGRAL_GB_RUNTIME_DEFAULT_PORT 25100u
#define INTEGRAL_GB_RUNTIME_LAN_REMOTE_DEFAULT_PORT 25170u
#define INTEGRAL_GB_RUNTIME_GB_WIDTH 160u
#define INTEGRAL_GB_RUNTIME_GB_HEIGHT 144u
#define INTEGRAL_GB_RUNTIME_RGB565_BYTES_PER_PIXEL 2u
#define INTEGRAL_GB_RUNTIME_AUDIO_SAMPLE_RATE 48000u
#define INTEGRAL_GB_RUNTIME_AUDIO_CHANNELS 2u
#define INTEGRAL_GB_RUNTIME_AUDIO_BYTES_PER_FRAME 4u
#define INTEGRAL_GB_RUNTIME_AUDIO_MAX_FRAMES 1024u
#define INTEGRAL_GB_RUNTIME_INPUT_PACKET_SIZE 13u
#define INTEGRAL_GB_RUNTIME_AUTH_TOKEN_SIZE 64u
#define INTEGRAL_GB_RUNTIME_AUTH_PACKET_SIZE (5u + INTEGRAL_GB_RUNTIME_AUTH_TOKEN_SIZE)
#define INTEGRAL_GB_RUNTIME_VIDEO_HEADER_SIZE 29u
#define INTEGRAL_GB_RUNTIME_VIDEO_PAYLOAD_SIZE (INTEGRAL_GB_RUNTIME_GB_WIDTH * INTEGRAL_GB_RUNTIME_GB_HEIGHT * INTEGRAL_GB_RUNTIME_RGB565_BYTES_PER_PIXEL)
#define INTEGRAL_GB_RUNTIME_VIDEO_PACKET_SIZE (1u + INTEGRAL_GB_RUNTIME_VIDEO_HEADER_SIZE + INTEGRAL_GB_RUNTIME_VIDEO_PAYLOAD_SIZE)
#define INTEGRAL_GB_RUNTIME_AUDIO_HEADER_SIZE 18u
#define INTEGRAL_GB_RUNTIME_AUDIO_PAYLOAD_SIZE (INTEGRAL_GB_RUNTIME_AUDIO_MAX_FRAMES * INTEGRAL_GB_RUNTIME_AUDIO_BYTES_PER_FRAME)
#define INTEGRAL_GB_RUNTIME_AUDIO_PACKET_SIZE (1u + INTEGRAL_GB_RUNTIME_AUDIO_HEADER_SIZE + INTEGRAL_GB_RUNTIME_AUDIO_PAYLOAD_SIZE)
#define INTEGRAL_GB_RUNTIME_UPLOAD_HEADER_SIZE 16u
#define INTEGRAL_GB_RUNTIME_UPLOAD_CLIENT_TIME_OFFSET 12u
#define INTEGRAL_GB_RUNTIME_SAVE_RETURN_HEADER_SIZE 4u
#define INTEGRAL_GB_RUNTIME_MAX_ROM_TRANSFER_BYTES (16u * 1024u * 1024u)
#define INTEGRAL_GB_RUNTIME_MAX_SAVE_TRANSFER_BYTES (2u * 1024u * 1024u)
#define INTEGRAL_GB_RUNTIME_SAVE_RETURN_PACKET_SIZE (1u + INTEGRAL_GB_RUNTIME_SAVE_RETURN_HEADER_SIZE + INTEGRAL_GB_RUNTIME_MAX_SAVE_TRANSFER_BYTES)
#define INTEGRAL_GB_RUNTIME_MAX_DOWNLINK_PACKET_SIZE INTEGRAL_GB_RUNTIME_SAVE_RETURN_PACKET_SIZE

enum {
    INTEGRAL_GB_RUNTIME_PACKET_VIDEO = 'V',
    INTEGRAL_GB_RUNTIME_PACKET_AUDIO = 'A',
    INTEGRAL_GB_RUNTIME_PACKET_SAVE_RETURN = 'S',
};

#define INTEGRAL_GB_RUNTIME_UPLOAD_MAGIC0 'F'
#define INTEGRAL_GB_RUNTIME_UPLOAD_MAGIC1 'G'
#define INTEGRAL_GB_RUNTIME_UPLOAD_MAGIC2 'U'
#define INTEGRAL_GB_RUNTIME_UPLOAD_MAGIC3 '1'
#define INTEGRAL_GB_RUNTIME_AUTH_MAGIC0 'F'
#define INTEGRAL_GB_RUNTIME_AUTH_MAGIC1 'G'
#define INTEGRAL_GB_RUNTIME_AUTH_MAGIC2 'A'
#define INTEGRAL_GB_RUNTIME_AUTH_MAGIC3 'T'
#define INTEGRAL_GB_RUNTIME_AUTH_MAGIC4 '1'

typedef enum IntegralGBRuntimeButton {
    INTEGRAL_GB_RUNTIME_BTN_RIGHT = 1u << 0,
    INTEGRAL_GB_RUNTIME_BTN_LEFT = 1u << 1,
    INTEGRAL_GB_RUNTIME_BTN_UP = 1u << 2,
    INTEGRAL_GB_RUNTIME_BTN_DOWN = 1u << 3,
    INTEGRAL_GB_RUNTIME_BTN_A = 1u << 4,
    INTEGRAL_GB_RUNTIME_BTN_B = 1u << 5,
    INTEGRAL_GB_RUNTIME_BTN_SELECT = 1u << 6,
    INTEGRAL_GB_RUNTIME_BTN_START = 1u << 7,
} IntegralGBRuntimeButton;

typedef struct IntegralGBRuntimeInputPacket {
    uint32_t seq;
    uint64_t client_timestamp_us;
    uint8_t buttons;
} IntegralGBRuntimeInputPacket;

typedef struct IntegralGBRuntimeVideoFrameHeader {
    uint32_t seq;
    uint64_t host_timestamp_us;
    uint16_t width;
    uint16_t height;
    uint8_t format;
    uint32_t last_applied_input_seq;
    uint64_t last_applied_client_timestamp_us;
} IntegralGBRuntimeVideoFrameHeader;

enum {
    INTEGRAL_GB_RUNTIME_PIXEL_FORMAT_RGB565 = 1,
};

static inline uint16_t integral_gb_runtime_rgb888_to_rgb565(uint32_t argb)
{
    uint8_t r = (uint8_t)(argb >> 16);
    uint8_t g = (uint8_t)(argb >> 8);
    uint8_t b = (uint8_t)argb;
    return (uint16_t)(((uint16_t)(r & 0xF8) << 8) |
                      ((uint16_t)(g & 0xFC) << 3) |
                      ((uint16_t)b >> 3));
}

#endif
